## Logistic Regression

THis is classification based algorithm that is used to predict target classes

Business Objective: Build a model that can predict species of Iris flower on basis of flower petal length/width and sepal length/width

## Step1: Data Gathering

In [1]:
import pandas as pd
path=r"https://raw.githubusercontent.com/sindhura-nk/Datasets/refs/heads/main/iris.csv"
df = pd.read_csv(path)
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

## Step2: Perform basic data quality checks

In [2]:
df.shape

(150, 5)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [4]:
df.duplicated().sum()

np.int64(1)

In [5]:
df=df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [6]:
# missing data
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

## Separate X and Y features

Predict Species: Y

In [7]:
X = df.drop(columns='species')
Y = df[['species']]
print("X records")
display(X.head())
print("Y records")
display(Y.head())

X records

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

Y records

  species
0  setosa
1  setosa
2  setosa
3  setosa
4  setosa

## Step4: SPlit the data into training and testing

    training: 80% and testing: 20%

In [8]:
from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest = train_test_split(X,Y,train_size=0.8,random_state=21)
print(xtrain.shape,xtest.shape)
print(ytrain.shape,ytest.shape)

(119, 4) (30, 4)
(119, 1) (30, 1)

## Data Processing: Data Cleaning

In [9]:
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer

num_pipe = make_pipeline(SimpleImputer(strategy='median')).set_output(transform="pandas")
num_pipe

Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median'))])

In [10]:
# fit it on training data
num_pipe.fit(xtrain)

Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median'))])

In [11]:
# transform it on testing as well as training data
xtrain_pre = num_pipe.transform(xtrain)
xtest_pre = num_pipe.transform(xtest)

In [12]:
xtrain_pre.head()

     sepal_length  sepal_width  petal_length  petal_width
41            4.5          2.3           1.3          0.3
130           7.4          2.8           6.1          1.9
70            5.9          3.2           4.8          1.8
46            5.1          3.8           1.6          0.2
125           7.2          3.2           6.0          1.8

In [13]:
xtest_pre.head()

    sepal_length  sepal_width  petal_length  petal_width
92           5.8          2.6           4.0          1.2
44           5.1          3.8           1.9          0.4
7            5.0          3.4           1.5          0.2
21           5.1          3.7           1.5          0.4
95           5.7          3.0           4.2          1.2

## Model Building: Logistic Regression

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
model = LogisticRegression()
model.fit(xtrain_pre,ytrain)

e:\Sindhura\3RI\ML 1663\repository\venv\Lib\site-packages\sklearn\utils\validation.py:1368: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [16]:
# training scores(accuracy)
model.score(xtrain_pre,ytrain)

0.9831932773109243

In [17]:
# testing scores(accuracy)
model.score(xtest_pre,ytest)

0.9333333333333333

## Training score as well testing scores are above 80%. We can consider this model. But for further evaluation,let's check for performance metrics

    precision
    recall
    f1_score
    accuracy

In [18]:
ytest_preds = model.predict(xtest_pre)
ytest_preds[:5]

array(['versicolor', 'setosa', 'setosa', 'setosa', 'versicolor'],
      dtype=object)

In [19]:
ytest.head()

       species
92  versicolor
44      setosa
7       setosa
21      setosa
95  versicolor

In [20]:
from sklearn.metrics import f1_score

In [22]:
f1_score_data = f1_score(ytest,ytest_preds,average='macro')
f1_score_data

0.9280303030303031